app/league/divisionPair/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, SubmitField, SelectField
from wtforms.validators import DataRequired


class DivisionPairForm(FlaskForm):
    id = HiddenField("ID")
    division_a = StringField('Division A', validators=[DataRequired()])
    division_b = StringField('Division B')
    location = StringField('Location', validators=[DataRequired()])
    weeknight = SelectField('Weeknight', choices=[('', 'Please Select'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ])
    table_string = StringField('Table String', validators=[DataRequired()])

    submit = SubmitField('Save')

app/league/divisionPair/__init__.py
from flask import Blueprint

bp = Blueprint('divisionPair', __name__)

from app.league.divisionPair import routes

app/league/divisionPair/routes.py
from flask import render_template, redirect, url_for, flash
from app.league.divisionPair import bp
from app.services.LeagueAPI import LeagueAPI
from app.league.divisionPair.forms import DivisionPairForm
from app.models import DivisionPair, MatchHistory
from app import db
from flask_login import login_required
import logging
from app.services.TableWizard import reassign_tables_for_division_pair


@bp.route('/divisionPair/', defaults={'DivisionPair_ID': None})
@bp.route('/divisionPair/<int:DivisionPair_ID>', methods=['GET', 'POST'])
@login_required
def index(DivisionPair_ID):
    pairs = DivisionPair.query.all()
    form = DivisionPairForm()

    return render_template('league/divisionPair/index.html', form=form, DivisionPair_ID=DivisionPair_ID, pairs=pairs)


@bp.route('/divisionPair/reassignTables/<int:DivisionPair_ID>', methods=['GET', 'POST'])
@login_required
def reassignTables(DivisionPair_ID):
    reassign_tables_for_division_pair(DivisionPair_ID)

    return redirect(url_for('divisionPair.matches', DivisionPair_ID=DivisionPair_ID))


@bp.route('/divisionPair/matches/<int:DivisionPair_ID>', methods=['GET', 'POST'])
@login_required
def matches(DivisionPair_ID):
    api = LeagueAPI("https://gql.poolplayers.com/graphql")
    league = api.query_league(slug='jacksonville')
    pair = DivisionPair.query.get(DivisionPair_ID)

    division_a_check = False
    division_b_check = False

    if pair.division_B == '':
        division_b_check = True

    division_a = None
    division_b = None

    # Fetch Divisions
    divisions = api.query_divisions(slug='jacksonville', session_id=league['data']['league']['currentSessionId'])

    for division in divisions['data']['league']['divisions']:
        if division['number'] == pair.division_A:
            division_a = division
            division_a_check = True
        if pair.division_B is not '' and division['number'] == pair.division_B:
            division_b = division
            division_b_check = True
        if division_a_check and division_b_check:
            break

    schedule_a = api.query_division_schedule(division_a['id']) if division_a else []
    schedule_b = api.query_division_schedule(division_b['id']) if division_b else []

    # Collect all match IDs from both schedules to retrieve assigned tables
    match_ids = [
        match['id'] for week in schedule_a['data']['division']['schedule'] for match in week['matches']
    ]
    if schedule_b:
        match_ids.extend([
            match['id'] for week in schedule_b['data']['division']['schedule'] for match in week['matches']
        ])

    # Retrieve table assignments from MatchHistory for the collected match IDs
    match_history_entries = MatchHistory.query.filter(MatchHistory.match_ID.in_(match_ids)).all()
    table_assignments = {entry.match_ID: entry.table_number for entry in match_history_entries}

    return render_template('league/divisionPair/matches.html', division_a=division_a, division_b=division_b,
                           schedule_a=schedule_a, schedule_b=schedule_b, DivisionPair_ID=DivisionPair_ID,
                           pair=pair, table_assignments=table_assignments)


@bp.route('/divisionPair/create', methods=['GET', 'POST'])
@login_required
def create_DivisionPair():
    form = DivisionPairForm()

    if form.validate_on_submit():
        new_pair = DivisionPair(
            division_A=form.division_a.data,
            division_B=form.division_b.data,
            location=form.location.data,
            weeknight=form.weeknight.data,
            table_string=form.table_string.data
        )

        db.session.add(new_pair)
        db.session.commit()

        return redirect(url_for('divisionPair.index'))

    return render_template('league/divisionPair/create.html', form=form)


@bp.route('/divisionPair/delete/<int:DivisionPair_ID>', methods=['GET', 'POST'])
@login_required
def delete_divisionPair(DivisionPair_ID):
    pair = DivisionPair.query.get(DivisionPair_ID)
    if pair:
        db.session.delete(pair)
        db.session.commit()
        return redirect(url_for('divisionPair.index'))


@bp.route('/divisionPair/edit/<int:DivisionPair_ID>', methods=['GET', 'POST'])
@login_required
def edit_divisionPair(DivisionPair_ID):
    form = DivisionPairForm()
    pair = DivisionPair.query.get(DivisionPair_ID)

    if form.validate_on_submit():

        pair = DivisionPair.query.get(DivisionPair_ID)
        pair.division_A = form.division_a.data,
        pair.division_B = form.division_b.data,
        pair.location = form.location.data,
        pair.weeknight = form.weeknight.data,
        pair.table_string = form.table_string.data

        db.session.commit()
        return redirect(url_for('divisionPair.index'))

    else:
        form.id = pair.id
        form.division_a.data = pair.division_A
        form.division_b.data = pair.division_B
        form.location.data = pair.location
        form.weeknight.data = pair.weeknight
        form.table_string.data = pair.table_string

    return render_template('league/divisionPair/edit.html', form=form)

app/templates/league/divisionPair/parts/editDivisionPair_Form.html
<form action="{{ url_for('divisionPair.edit_divisionPair', DivisionPair_ID=form.id) }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="w3-row-padding">
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.division_a.label }}</label>
            {{ form.division_a(class_="w3-input w3-border w3-round") }}
        </div>
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.division_b.label }}</label>
            {{ form.division_b(class_="w3-input w3-border w3-round") }}
        </div>
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.location.label }}</label>
            {{ form.location(class_="w3-input w3-border w3-round") }}
        </div>
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.weeknight.label }}</label>
            {{ form.weeknight(class_="w3-select w3-border w3-round") }}
        </div>
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.table_string.label }}</label>
            {{ form.table_string(class_="w3-input w3-border w3-round") }}
        </div>

        <div class="w3-col m4 w3-margin-bottom w3-center" style="padding-top: 24px;">
            {{ form.submit(class_="w3-button w3-green w3-round") }}
        </div>
    </div>
</form>

app/templates/league/divisionPair/parts/listDivisionPair_All.html
<div class="w3-container w3-margin-top">
    <br>
    <h1 class="matches-title w3-xxlarge w3-center">Division Pairs</h1>

    <div class="w3-card-4 w3-padding w3-round-large w3-light-grey w3-animate-opacity">
        <table class="w3-table w3-table-all w3-hoverable w3-bordered w3-centered w3-large w3-white w3-striped">
                <th></th>
                <th class="w3-hover-dark-grey" onclick="w3.sortHTML('#divisionPairsTable', '.pairRow', 'td:nth-child(1)')">
                    Division A
                </th>
                <th class="w3-hover-dark-grey" onclick="w3.sortHTML('#divisionPairsTable', '.pairRow', 'td:nth-child(2)')">
                    Division B
                </th>
                <th class="w3-hover-dark-grey" onclick="w3.sortHTML('#divisionPairsTable', '.pairRow', 'td:nth-child(3)')">
                    Location
                </th>
                <th class="w3-hover-dark-grey" onclick="w3.sortHTML('#divisionPairsTable', '.pairRow', 'td:nth-child(4)')">
                    Weeknight
                </th>
                <th class="w3-hover-dark-grey" onclick="w3.sortHTML('#divisionPairsTable', '.pairRow', 'td:nth-child(5)')">
                    Table String
                </th>
                <th></th>
            <tbody id="divisionPairsTable">
            <!-- The initial data is loaded here, but it will be updated dynamically with JavaScript -->
            {% for pair in pairs %}
            <tr class="pairRow">
                <td><a href="{{ url_for('divisionPair.matches', DivisionPair_ID=pair.id) }}">Matches</a></td>
                <td>{{ pair.division_A }}</td>
                <td>{{ pair.division_B }}</td>
                <td>{{ pair.location }}</td>
                <td>{{ pair.weeknight }}</td>
                <td>{{ pair.table_string }}</td>
                <td><a href="{{ url_for('divisionPair.edit_divisionPair', DivisionPair_ID=pair.id) }}">Edit</a> - <a href="{{ url_for('divisionPair.delete_divisionPair', DivisionPair_ID=pair.id) }}">Delete</a></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <br>
        <a href="{{ url_for('divisionPair.create_DivisionPair') }}">New Division Pair</a>
    </div>
</div>

app/templates/league/divisionPair/parts/newDivisionPair_Form.html
<form action="{{ url_for('divisionPair.create_DivisionPair') }}" method="POST">
    {{ form.hidden_tag() }}
    <div class="w3-row-padding">
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.division_a.label }}</label>
            {{ form.division_a(class_="w3-input w3-border w3-round") }}
        </div>
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.division_b.label }}</label>
            {{ form.division_b(class_="w3-input w3-border w3-round") }}
        </div>
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.location.label }}</label>
            {{ form.location(class_="w3-input w3-border w3-round") }}
        </div>
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.weeknight.label }}</label>
            {{ form.weeknight(class_="w3-select w3-border w3-round") }}
        </div>
        <div class="w3-col m8 w3-margin-bottom">
            <label>{{ form.table_string.label }}</label>
            {{ form.table_string(class_="w3-input w3-border w3-round") }}
        </div>

        <div class="w3-col m4 w3-margin-bottom w3-center" style="padding-top: 24px;">
            {{ form.submit(class_="w3-button w3-green w3-round") }}
        </div>
    </div>
</form>

app/templates/league/divisionPair/parts/tonights_matches.html
<div class="w3-container w3-margin-top">
    <br>
    <h1 class="matches-title w3-xxlarge w3-center">
        Tonight's Matches - {{ division_a['number'] }}
        {% if division_b %} & {{ division_b['number'] }}{% endif %}
    </h1>
    <p>Table String: {{ pair.table_string }}</p>

    <form action="{{ url_for('divisionPair.reassignTables', DivisionPair_ID=pair.id) }}" method="post">
        <button type="submit" class="w3-button w3-blue">Reassign Tables (All Matches)</button>
    </form>

    <div class="w3-container w3-margin-bottom">
        <div class="w3-row w3-center w3-padding-small w3-margin-top">
            <div class="w3-col s4 w3-left-align">
                <button class="w3-button w3-light-grey" onclick="changeDate(-1)" style="width: 80%;">&#10094; Previous Day</button>
            </div>
            <div class="w3-col s4">
                <span class="w3-large w3-padding" id="selectedDate" style="font-weight: bold;"></span>
            </div>
            <div class="w3-col s4 w3-right-align">
                <button class="w3-button w3-light-grey" onclick="changeDate(1)" style="width: 80%;">Next Day &#10095;</button>
            </div>
        </div>
        <div class="w3-center">
            <button class="w3-button w3-blue" onclick="toggleDisplayMode()" id="toggleButton">Show All Matches</button>
        </div>
    </div>

    <div class="w3-card-4 w3-padding w3-round-large w3-light-grey w3-animate-opacity">
        <table class="w3-table w3-table-all w3-hoverable w3-bordered w3-centered w3-large w3-white w3-striped">
            <thead>
                <tr>
                    <th class="w3-hover-dark-grey" onclick="w3.sortHTML('#matchTable', '.matchRow', 'td:nth-child(1)')">Match Date</th>
                    <th class="w3-hover-dark-grey" onclick="w3.sortHTML('#matchTable', '.matchRow', 'td:nth-child(2)')">Home Team</th>
                    <th class="w3-hover-dark-grey" onclick="w3.sortHTML('#matchTable', '.matchRow', 'td:nth-child(3)')">Away Team</th>
                    <th class="w3-hover-dark-grey" onclick="w3.sortHTML('#matchTable', '.matchRow', 'td:nth-child(4)')">Match Type</th>
                    <th>Table(s)</th>
                </tr>
            </thead>
            <tbody id="matchTable"></tbody>
        </table>
    </div>
</div>

<script src="https://www.w3schools.com/lib/w3.js"></script>
<script>
    // Store assigned tables data passed from the backend
    const tableAssignments = {{ table_assignments | tojson }};

    let divisionData_a = {
        format: {{ schedule_a['data']['division']['format'] | tojson }},
        schedule: {{ schedule_a['data']['division']['schedule'] | tojson }}
    };

    // Only define `divisionData_b` if `schedule_b` exists
    {% if schedule_b %}
    let divisionData_b = {
        format: {{ schedule_b['data']['division']['format'] | tojson }},
        schedule: {{ schedule_b['data']['division']['schedule'] | tojson }}
    };
    {% endif %}

    // Combine schedules while keeping track of division formats
    let matchesData = [
        ...divisionData_a.schedule.map(week => ({ ...week, format: divisionData_a.format })),
        {% if schedule_b %}
        ...divisionData_b.schedule.map(week => ({ ...week, format: divisionData_b.format }))
        {% endif %}
    ];

    let currentDate = new Date();
    let displayAllMatches = false; // Toggle state to show all matches or today's matches

    // Function to format date as yyyy-mm-dd
    function formatDate(date) {
        return date.toISOString().split('T')[0];
    }

    // Function to change the displayed date
    function changeDate(days) {
        currentDate.setDate(currentDate.getDate() + days);
        updateMatches();
    }

    // Function to toggle display mode between all matches and today's matches
    function toggleDisplayMode() {
        displayAllMatches = !displayAllMatches;
        document.getElementById('toggleButton').innerText = displayAllMatches ? "Show Specific Date Matches" : "Show All Matches";
        updateMatches();
    }

    // Function to update matches based on the selected date or all dates
    function updateMatches() {
        // Update the displayed date if showing today's matches
        document.getElementById('selectedDate').innerText = displayAllMatches ? "All Dates" : currentDate.toDateString();

        // Clear existing table rows
        let matchTable = document.getElementById('matchTable');
        matchTable.innerHTML = '';

        // Format the current date to match the date format in the data
        let selectedDateString = formatDate(currentDate);

        // Accumulate matches for the selected date or all dates
        let matchesForDisplay = [];
        matchesData.forEach(week => {
            let weekDate = new Date(week.date);
            if (displayAllMatches || formatDate(weekDate) === selectedDateString) {
                week.matches.forEach(match => {
                    matchesForDisplay.push({
                        match: match,
                        format: week.format,
                        date: formatDate(weekDate) // Store the date for each match
                    });
                });
            }
        });

        // Add the accumulated matches to the table
        matchesForDisplay.forEach(({ match, format, date }) => {
            // Get the assigned table number for the match or default to "X" if not assigned
            const assignedTable = tableAssignments[match.id] || "X";
            let row = `<tr class="matchRow w3-hover-light-grey">
                            <td>${date}</td>
                            <td>${match.home.name} (${match.home.number})</td>
                            <td>${match.away.name} (${match.away.number})</td>
                            <td>${format}</td>
                            <td>${assignedTable}</td>
                       </tr>`;
            matchTable.innerHTML += row;
        });

        // If no matches are found for the selected display mode, show a message
        if (matchesForDisplay.length === 0) {
            let row = `<tr class="matchRow w3-hover-light-grey">
                            <td colspan="5" class="w3-text-red w3-center">No matches scheduled for this date.</td>
                       </tr>`;
            matchTable.innerHTML += row;
        }
    }

    // Initial update for today's matches
    updateMatches();
</script>